In [2]:
import pandas as pd

doctor_df = pd.read_csv('./전문의 현황.csv')
doctor_df

,시도별(1),2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,시도별(1),의사,의사,의사,의사,의사,의사,의사,의사,의사,의사,의사,의사,의사,의사,의사
1,시도별(1),전문의,전문의,전문의,전문의,전문의,전문의,전문의,전문의,전문의,전문의,전문의,전문의,전문의,전문의,전문의
2,계,56028,58857,58722,64461,67574,70609,73110,75550,78282,81041,83147,86122,88877,91053,93457
3,서울특별시,15316,16200,16102,17816,18667,19423,19953,20361,21040,21698,22352,23359,24290,25109,25806
4,부산광역시,4379,4568,4698,5167,5369,5631,5822,6021,6196,6317,6465,6669,6835,6966,7100
5,대구광역시,3236,3404,3370,3634,3814,3941,4023,4174,4350,4462,4620,4813,4953,5060,5180
6,인천광역시,2419,2537,2511,2797,2951,3142,3347,3548,3686,3900,4085,4250,4349,4433,4554
7,광주광역시,1945,1990,2024,2225,2351,2451,2572,2686,2785,2869,2937,3045,3089,3092,3186
8,대전광역시,2000,2101,2136,2248,2395,2477,2566,2647,2731,2829,2917,2990,2981,3026,3066
9,울산광역시,1030,1073,1055,1163,1211,1252,1298,1380,1442,1483,1484,1528,1543,1570,1588
10,세종특별자치시,-,-,-,-,72,82,110,147,164,218,247,276,408,430,464
11,경기도,10806,11402,11362,12603,13365,14057,14536,15094,15713,16559,17223,18024,19000,19686,20719
12,강원특별자치도,1538,1594,1626,1713,1771,1838,1897,1947,1978,2013,2051,2106,2183,2211,2228
13,충청북도,1415,1491,1480,1624,1667,1752,1824,1913,1998,2040,2088,2119,2135,2139,2171
14,충청남도,1838,1901,1864,2028,2072,2174,2259,2357,2436,2499,2501,2567,2625,2668,2673
15,전라북도,2083,2172,2175,2354,2431,2541,2630,2749,2825,2904,2895,2974,2962,2994,2998
16,전라남도,1898,2004,1984,2161,2236,2353,2425,2495,2546,2581,2533,2553,2564,2616,2615
17,경상북도,2444,2530,2505,2712,2804,2919,3048,3060,3125,3201,3204,3198,3181,3167,3168
18,경상남도,3094,3277,3204,3550,3684,3791,3985,4105,4362,4508,4561,4638,4753,4856,4891
19,제주특별자치도,587,613,626,666,714,785,815,866,905,960,984,1013,1026,1030,1050

In [4]:
import pandas as pd

doctor_df = pd.read_csv('./total doctor.csv')
doctor_df

,행정구역별,2014,2014.1,2014.2,2015,2015.1,2015.2,2016,2016.1,2016.2,...,2020.2,2021,2021.1,2021.2,2022,2022.1,2022.2,2023,2023.1,2023.2
0,행정구역별,인구 천명당 의료기관 종사 의사수<br>(A÷B×1000),의료기관 종사 의사수<br>(A),주민등록인구<br>(B),인구 천명당 의료기관 종사 의사수<br>(A÷B×1000),의료기관 종사 의사수<br>(A),주민등록인구<br>(B),인구 천명당 의료기관 종사 의사수<br>(A÷B×1000),의료기관 종사 의사수<br>(A),주민등록인구<br>(B),...,주민등록인구<br>(B),인구 천명당 의료기관 종사 의사수<br>(A÷B×1000),의료기관 종사 의사수<br>(A),주민등록인구<br>(B),인구 천명당 의료기관 종사 의사수<br>(A÷B×1000),의료기관 종사 의사수<br>(A),주민등록인구<br>(B),인구 천명당 의료기관 종사 의사수<br>(A÷B×1000),의료기관 종사 의사수<br>(A),주민등록인구<br>(B)
1,전국,2.6,134646,51327916,2.7,137862,51529338,2.7,141600,51696216,...,51829023,3.1,159970,51638809,3.2,163115,51439038,3.2,166197,51325329
2,서울특별시,3.8,38625,10103233,3.9,39026,10022181,4.0,39640,9930616,...,9668465,4.7,44717,9509458,4.8,45440,9428372,5.0,46624,9386034
3,부산광역시,3.0,10458,3519401,3.1,10745,3513777,3.1,10929,3498529,...,3391946,3.5,11778,3350380,3.6,11982,3317812,3.7,12120,3293362
4,대구광역시,3.0,7360,2493264,3.0,7557,2487829,3.1,7792,2484557,...,2418346,3.6,8661,2385412,3.7,8810,2363691,3.8,9006,2374960
5,인천광역시,2.1,6075,2902608,2.1,6279,2925815,2.2,6465,2943069,...,2942828,2.6,7621,2948375,2.6,7857,2967314,2.7,8187,2997410
6,광주광역시,3.2,4740,1475884,3.3,4885,1472199,3.5,5104,1469214,...,1450062,3.7,5382,1441611,3.8,5488,1431050,3.9,5552,1419237
7,대전광역시,3.1,4762,1531809,3.2,4879,1518775,3.3,4962,1514370,...,1463882,3.7,5348,1452251,3.7,5406,1446072,3.8,5419,1442216
8,울산광역시,2.0,2372,1166377,2.1,2504,1173534,2.2,2593,1172304,...,1136017,2.4,2714,1121592,2.5,2737,1110663,2.5,2790,1103661
9,세종특별자치시,1.3,208,156125,1.3,274,210884,1.3,323,243048,...,355831,1.9,721,371895,2.0,770,383591,2.1,811,386525
10,경기도,2.1,25826,12357830,2.1,26720,12522606,2.2,27728,12716780,...,13427014,2.5,33919,13565450,2.6,35401,13589432,2.7,36309,13630821
11,강원특별자치도,2.3,3548,1544442,2.3,3634,1549507,2.4,3696,1550806,...,1542840,2.7,4079,1538492,2.7,4077,1536498,2.7,4098,1527807
12,충청북도,2.1,3299,1578933,2.2,3417,1583952,2.2,3523,1591625,...,1600837,2.4,3848,1597427,2.4,3884,1595058,2.4,3896,1593469
13,충청남도,2.1,4395,2062273,2.2,4476,2077649,2.2,4584,2096727,...,2121029,2.4,5057,2119257,2.4,5052,2123037,2.4,5132,2130119
14,전라북도,2.7,5024,1871560,2.8,5205,1869711,2.8,5292,1864791,...,1804104,3.1,5560,1786855,3.1,5574,1769607,3.2,5599,1754757
15,전라남도,2.2,4256,1905780,2.3,4333,1908996,2.4,4482,1903914,...,1851549,2.6,4816,1832803,2.6,4801,1817697,2.6,4750,1804217
16,경상북도,1.9,5206,2700794,1.9,5212,2702826,2.0,5315,2700398,...,2639422,2.1,5636,2626609,2.2,5624,2600492,2.2,5638,2554324
17,경상남도,2.1,7127,3350257,2.2,7278,3364702,2.3,7674,3373871,...,3340216,2.5,8371,3314183,2.6,8432,3280493,2.6,8465,3251158
18,제주특별자치도,2.2,1365,607346,2.3,1438,624395,2.3,1498,641597,...,674635,2.6,1742,676759,2.6,1780,678159,2.7,1801,675252